Enabled persistence for Firebase database & some other fixes
androidthings/doorbell pull request #5
Opened 2017-01-03 19:42 UTC by riggaroo

Hi there, 
Thanks so much for this fun example of Android Things! I've made some improvements to the companion app, please see the pull request if you would like to merge the changes. 

Changes:
- Enabled persistence for Firebase database to speed up the loading of
the data on the client side (initial loading seems slow still but this will speed up further requests), I've also moved the initialization of the adapter into onCreate and onDestroy as it was reloading the data every time the app paused for a bit, this should also improve the performance a bit. 
- Updated version numbers of firebase dependencies from 9.4.0 to 10.0.1
- Made the companion app target minSdkVersion 21 as there was nothing stopping this from working on lower device levels.
- Code cleanup of doorbell_entry.xml to use better naming for Views.

Let me know if there is anything wrong with the contribution.

2017-01-09 21:18 UTC, proppy requested changes
Thanks a lot for the contribution!

I'll let @devunwired or @jdkoren comment on the Android tweaks.

2017-01-09 21:18 UTC, proppy commented on companionApp/src/main/res/layout/doorbell_entry.xml
> +        android:id="@+id/imageViewCapture" />
shouldn't `DoorbellEntryAdapter.java` also be updated with those new names?

2017-01-12 16:15 UTC, riggaroo commented on companionApp/src/main/res/layout/doorbell_entry.xml
> +        android:id="@+id/imageViewCapture" />
I have updated the pull request.

2017-01-12 21:57 UTC, proppy approved these changes

2017-01-12 21:58 UTC, proppy commented
also pinging @shawngit  :)

2017-01-12 22:11 UTC, jdkoren reviewed
UI changes seem fine, but I don't know anything about using Firebase and related adapters, so I'll defer to others who do.

2017-01-12 22:11 UTC, jdkoren commented on companionApp/src/main/AndroidManifest.xml
> +          package="com.example.androidthings.doorbell">
nit: extra whitespace

2017-01-13 17:12 UTC, riggaroo commented on companionApp/src/main/AndroidManifest.xml
> +          package="com.example.androidthings.doorbell">
I have fixed this.

2019-02-01 12:21 UTC, closed without merging